server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
      item-service : /item/**
      search-service: /search/**
      user-service: /user/**
      auth-service: /auth/** # 授权中心微服务
      cart-service: /cart/** #购物车微服务
  add-host-header: true #将cookie加入到请求头当中
  sensitive-headers: #配置禁止使用的头信息，这里设置为null，否则set-cookie无效
leyou:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item